version: '3.9'

services:
  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./test-task-data:/test-task-data
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test_db
